version: '3'
services:
  api:
    build: .
    container_name: books-api
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      PASSWORD: changeme
      MARIA_DB: books
      USER_NAME: root
      HOST: mariadb
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.2
    container_name: maria-db
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: books
      MYSQL_USER: book
      MYSQL_PASSWORD: changeme
    volumes:
     - ./data/mariadb:/var/lib/mysql